### ISSUE TITLE
Large Updates Coming Soon

### ISSUE THREAD

**Issue by Degen-dev** [Degen-dev/Degeneracy#10]
Not an issue, but more of an announcement, but Degeneracy is getting a large update soon. It will basically contain a rewrite of the existing HTML, CSS, and frontend JS to be much cleaner and to make much more sense, however the frontend will still look the same. This update will also most likely contain Ultraviolet and will get rid of Corrosion.

**Comment by Degen-dev** [comment]
These updates have been (mostly) applied to all official links. The changes will be made open source shortly!

**Comment by BuggyThe1st** [comment]
This is pretty strange to ask but can you list all the official links?

**Comment by Degen-dev** [comment]
That's a perfectly normal request. To get the full list of links, I'd have to request that you join the [Titanium Network discord](https://discord.gg/unblock)! There I regularly post new links and give updates!

**Comment by BuggyThe1st** [comment]
Ok. Thank you.

**Comment by Degen-dev** [comment]
Updates made
