### ISSUE TITLE
Proxy issue?

### ISSUE THREAD

**Issue by ToasterWaffl** [Degen-dev/Degeneracy#12]
Proxy issue with womngix 
Go to the website and click womgix then click discord , the website returns a blank white page 
Is this a issue with womgnix?

**Comment by Degen-dev** [comment]
Is this issue occurring for you on all of the links, or just one?

**Comment by ToasterWaffl** [comment]
Mainly womgnix I can’t use captcha with rhodium

**Comment by Degen-dev** [comment]
Could you post the url you are using for Degeneracy?

**Comment by ToasterWaffl** [comment]
pleasedontblock.me

**Comment by ToasterWaffl** [comment]
I’m using iOS this happened before with another proxy

**Comment by Degen-dev** [comment]
On iOS, I was able to recreate the issue. It appears that womginx itself doesn't work on iOS browsers i.e. Safari. I will see what I can do about this, maybe reverting back to an older version of womginx.

**Comment by ToasterWaffl** [comment]
A older version of womgnix worked before

**Comment by Degen-dev** [comment]
It looks like womginx has gotten a commit that fixed this. I will apply this to my instance as soon as possible.

**Comment by Degen-dev** [comment]
I have updated womginx to the latest commit, and discord now works on my iOS device. Please alert me on whether or not it works for you now.

**Comment by ToasterWaffl** [comment]
It’s working on my end

**Comment by ToasterWaffl** [comment]
It was working I can still access discord so it’s working on your end I think womginx in general is suffering

**Comment by ToasterWaffl** [comment]
It works

**Comment by Degen-dev** [comment]
Nice! I will be closing this issue now, as the issue is resolved.
