### ISSUE TITLE
how to host it publicly 

### ISSUE THREAD

**Issue by WindowsRefundDay** [Degen-dev/Degeneracy#17]
me again😅
I'm trying to host degeneracy and when I visit the ip address of my pi it shows the nginxs successfully installed screen and also what port is it hosted on.

**Comment by Degen-dev** [comment]
Degeneracy by default is hosted on port `8443`. The method that is listed in the readme will only display degeneracy on a link.

**Comment by WindowsRefundDay** [comment]
also for making a  file at /etc/nginx/sites-enabled/degeneracy, what is the format?

**Comment by Degen-dev** [comment]
Could you specify on what you mean by "format"?
