### ISSUE TITLE
its blocked

### ISSUE THREAD

**Issue by pwksmsmsm** [Degen-dev/Degeneracy#20]
blocked

**Comment by pwksmsmsm** [comment]
what filters?

**Comment by Degen-dev** [comment]
iBoss, GoGuardian, Securly, etc.

**Comment by pwksmsmsm** [comment]
what are those

**Comment by Degen-dev** [comment]
Those are web filters. The "blockers" if you will.

**Comment by Degen-dev** [comment]
I believe you are confused. You wouldn't "go" to the filter. The filter is traditionally preinstalled on your school-issued device. It's the thing that blocks websites.

**Comment by pwksmsmsm** [comment]
do you have any working proxys

**Comment by Degen-dev** [comment]
> Join the [Titanium Network discord](https://discord.gg/unblock). There I regularly post new links and give updates!
#19

**Comment by pwksmsmsm** [comment]
i cant its blocked

**Comment by Degen-dev** [comment]
Okay, try using https://geohelp.xyz. Is that blocked?

**Comment by pwksmsmsm** [comment]
yes
itd blocked

**Comment by pwksmsmsm** [comment]
do u have a diffrent oen

**Comment by pwksmsmsm** [comment]
hello?

**Comment by Degen-dev** [comment]
There isn't much I can do in that case.

**Comment by pwksmsmsm** [comment]
:(

**Comment by pwksmsmsm** [comment]
u dont have any proxys?

**Comment by pwksmsmsm** [comment]
i really need proxy

**Comment by pwksmsmsm** [comment]
hey
