### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ThatOneKidAtSchool** [Degen-dev/Degeneracy#8]
Error in ip adress
![121E49B1-D1AC-474F-9EC9-719603ACD5BD](https://user-images.githubusercontent.com/98852229/154556539-8e995104-7c8b-480c-88b4-9646ff7ee80f.jpeg)

**Comment by Degen-dev** [comment]
My Porkbun account was suspended for an unknown reason. I will do my best to get Degeneracy back up as soon as possible, however there isn't much I can do right now, sadly. I recommend using [Ludicrous](https://github.com/LudicrousDevelopment/Ludi-2) while Degeneracy is down. I apologize for the inconvenience.

**Comment by Degen-dev** [comment]
The suspension was lifted. Degeneracy is back up :)
